apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-depl
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username         
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password       
          - name: ME_CONFIG_MONGODB_SERVER    
            valueFrom:
              configMapKeyRef:
                name: mongo-configmap
                key:  database_url
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express   #must be the same as the label in the deployment
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000