apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-depl
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: sepid5689/my-app:3.0
          ports:
            - containerPort: 3000
          # env:
          # - name: MONGODB_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: mongo-secret
          #       key: username         
          # - name: MONGODB_PASSWORD 
          #   valueFrom:
          #     secretKeyRef:
          #       name: mongo-secret
          #       key: password       
         
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app   #must be the same as the label in the deployment
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000