name: Docker Image build and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    name: Build Docker image and push it to docker hub
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: log into docker hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sepid5689/my-app:3.0
    - name: push docker image
      run: docker push sepid5689/my-app:3.0